# Generated by Django 3.2.19 on 2023-06-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_myuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'пользователей'},
        ),
    ]
